### ISSUE TITLE
include latex source?

### ISSUE THREAD

**Issue by dkg** [chelseakomlo/e2ee#1]
@chelseakomlo thanks for writing up this definition.  Can you include the latex source in this repo, rather than just the pdf output?  it would make it easier to propose specific clarifications or at least raise specific questions about the game formulation.

For example, in figure 1 of the pdf, we see 𝓡 and 𝓢 being set during initialization, but later we see R and S.  Should those be normalized?  If R and S are specific elements of sets 𝓡 and 𝓢 (respectively), then how does their assignment from _Initialize_ correspond to the assignment for b' ?

**Comment by chelseakomlo** [comment]
Hi @dkg , thanks for the message. Britta and I just put out an updated draft here: https://eprint.iacr.org/2022/449

I'll open an issue against draft-knodel-e2ee-definition to update the reference. 

If you would still like to see the latex source for this updated draft, please let me know.
